# Generated by Django 4.0.6 on 2022-07-23 22:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('Espn_League_Id', models.IntegerField()),
                ('Espn_S2', models.CharField(max_length=3000)),
                ('Espn_SWID', models.CharField(max_length=300)),
            ],
        ),
    ]
