# Generated by Django 4.0.1 on 2022-07-25 21:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_espn_swid_league_espn_swid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('Espn_League_Id', models.IntegerField(unique=True)),
                ('Espn_S2', models.CharField(max_length=3000)),
                ('Espn_Swid', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
