# Generated by Django 4.0.1 on 2022-07-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_league_league_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_mod',
            name='bigdata',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
