# Generated by Django 4.0.1 on 2022-07-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_league_mod_bigdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_mod',
            name='code',
        ),
    ]
