# Generated by Django 4.0.1 on 2022-07-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_league_mod_bigdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_mod',
            name='year_started',
            field=models.IntegerField(default=0),
        ),
    ]
