# Generated by Django 4.0.1 on 2022-07-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_mod',
            name='standings',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
