# Generated by Django 4.0.1 on 2022-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_league_mod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_mod',
            name='owners',
            field=models.JSONField(default=list, null=True),
        ),
    ]
