# Generated by Django 4.0.1 on 2022-08-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_league_mod_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_mod',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
